for i, v in game.Players.LocalPlayer.Character:WaitForChild('EquippedAccessories'):GetChildren() do game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('UnequipItem'):FireServer(v.Name) end
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("- Hair 3")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("- Hair 3", '1', Color3.new(0.7921568751335144, 0.6352941393852234, 0.5176470875740051))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("- Hair 3", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Trench Coat")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Trench Coat", '1', Color3.new(1, 0.545098066329956, 0.5607843399047852))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Trench Coat", '2', Color3.new(1, 0.545098066329956, 0.5607843399047852))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Trench Coat", '3', Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Trench Coat", 1, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Basic Top")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Basic Top", '1', Color3.new(1, 0.545098066329956, 0.5607843399047852))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer("Basic Top", '1', 'ClothingSilkLight')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Basic Top", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Basic Skirt")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Basic Skirt", '1', Color3.new(1, 0.545098066329956, 0.5607843399047852))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Basic Skirt", 1, {["High"] = "Off", ["Slit"] = "On"})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Classic Heels")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Classic Heels", '1', Color3.new(1, 0.545098066329956, 0.5607843399047852))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Classic Heels", '2', Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Classic Heels", 1, {["Pointy"] = "Off"})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Tinted Glasses")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Tinted Glasses", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer("Tinted Glasses", '1', 'MattePlastic')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Tinted Glasses", '2', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Tinted Glasses", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ChangeNailStyle'):FireServer('Default')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer('Nails', '1', Color3.new(0.9803921580314636, 0.6784313917160034, 0.501960813999176))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer('Nails', '1', 'MattePlastic')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ChangeSkintone'):FireServer(Color3.new(0.800000011920929, 0.5568627715110779, 0.4117647111415863))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ClassicMakeup'):FireServer(227, 'Light')
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 185, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 185, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 185, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyebrows', 115, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Contour', 53, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 400, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 2)
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Lips', 185, 1, Color3.new(0.8464530110359192, 0.4704495668411255, 0.4704495668411255))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Lips', 185, 2, Color3.new(1, 0.6229726076126099, 0.6229726076126099))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 190, 2, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyebrows', 115, 1, Color3.new(0.741394579410553, 0.741394579410553, 0.741394579410553))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 190, 1, Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Contour', 53, 1, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 400, 1, Color3.new(1, 1, 1))
