game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('ClassicMakeup'):FireServer(227, "Light)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 188, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 188, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 188, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyebrows', 155, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 401, 5)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 405, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 398, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Contour', 50, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 404, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 190, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 400, 4)
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Lips', 188, 1, Color3.new(0.4117647111415863, 0.0470588244497776, 0.054901961237192154))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 190, 2, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyebrows', 155, 1, Color3.new(0.364705890417099, 0.29411765933036804, 0.239215686917305))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 401, 5, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 190, 1, Color3.new(0.4117647111415863, 0.0470588244497776, 0.054901961237192154))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 405, 3, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 398, 2, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Contour', 50, 1, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 404, 1, Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 400, 4, Color3.new(1, 1, 1))
