for i, v in game.Players.LocalPlayer.Character:WaitForChild('EquippedAccessories'):GetChildren() do game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('UnequipItem'):FireServer(v.Name) end
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Fishnets")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Fishnets", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Fishnets", 1, {["Feet"] = "On", ["Thick"] = "Off"})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Fur Legs")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Fur Legs", '1', Color3.new(0.9725490212440491, 0.9725490212440491, 0.9725490212440491))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Fur Legs", '1', 'rbxassetid://130990478953349')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Fur Legs", 1, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Classic Heels")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Classic Heels", '1', Color3.new(0.06666667014360428, 0.06666667014360428, 0.06666667014360428))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer("Classic Heels", '1', 'MattePlastic')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Classic Heels", '2', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Classic Heels", 1, {["Pointy"] = "Off"})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Jeans F: Shorts")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Jeans F: Shorts", '1', Color3.new(0.5568627715110779, 0.5803921818733215, 0.6313725709915161))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Jeans F: Shorts", '1', 'rbxassetid://130990478953349')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Jeans F: Shorts", '2', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Jeans F: Shorts", 4, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Sleepy Heart Top")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Sleepy Heart Top", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Sleepy Heart Top", '2', Color3.new(0.8039215803146362, 0.0941176488995552, 0.5176470875740051))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Sleepy Heart Top", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Punk Arm Bands")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Punk Arm Bands", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Punk Arm Bands", '1', 'rbxassetid://130990478953349')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Punk Arm Bands", '2', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Punk Arm Bands", '3', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Punk Arm Bands", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Belt")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Belt", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Belt", '2', Color3.new(1, 1, 1))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Belt", 3, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("Mesh Top")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("Mesh Top", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("Mesh Top", 3, {["Thick"] = "Off"})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("y2k Flip Phone")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("y2k Flip Phone", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("y2k Flip Phone", '2', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer("y2k Flip Phone", '2', 'Neon')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("y2k Flip Phone", '3', Color3.new(1, 0.11372549086809158, 0.6431372761726379))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer("y2k Flip Phone", '3', 'Neon')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("y2k Flip Phone", '4', Color3.new(1, 0.9333333969116211, 0.9333333969116211))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("y2k Flip Phone", 2, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("- Hair Spikey Bun")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("- Hair Spikey Bun", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("- Hair Spikey Bun", '2', Color3.new(0.3529411852359772, 0, 0.1725490242242813))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("- Hair Spikey Bun", 0, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('EquipItem'):FireServer("- Hair Scene Girl")
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("- Hair Scene Girl", '1', Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer("- Hair Scene Girl", '2', Color3.new(0.3529411852359772, 0, 0.1725490242242813))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('DressUpToggle'):FireServer("- Hair Scene Girl", 2, {})
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ChangeNailStyle'):FireServer('Coffin')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ColorAccessory'):FireServer('Nails', '1', Color3.new(1, 0.11372549086809158, 0.6431372761726379))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('MaterialAccessory'):FireServer('Nails', '1', '')
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ChangeSkintone'):FireServer(Color3.new(0.3019607961177826, 0.20392157137393951, 0.125490203499794))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ClassicMakeup'):FireServer(227, 'Light')
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 161, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 161, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Lips', 161, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 192, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyebrows', 111, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 192, 3)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 373, 2)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Contour', 53, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Touches', 277, 1)
game.ReplicatedStorage:WaitForChild('RemoteEvents'):WaitForChild('CustomMakeup'):FireServer('Eyes', 192, 2)
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Lips', 161, 1, Color3.new(0.7090688943862915, 0.4979972243309021, 0.4716132879257202))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Lips', 161, 2, Color3.new(0.2888350486755371, 0.16829758882522583, 0.14782896637916565))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyebrows', 111, 1, Color3.new(0.21610227227210999, 0.21610227227210999, 0.21610227227210999))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 192, 2, Color3.new(0, 0, 0))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 373, 2, Color3.new(0.7211909890174866, 0, 0.4726336896419525))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Contour', 53, 1, Color3.new(0.474707692861557, 0.474707692861557, 0.474707692861557))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Touches', 277, 1, Color3.new(0.5353183746337891, 0.5353183746337891, 0.5353183746337891))
game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('ApplyMakeupColor'):FireServer('Eyes', 192, 1, Color3.new(0, 0, 0))
