for i, v in game.Players.LocalPlayer.Character:WaitForChild('EquippedAccessories'):GetChildren() do game:GetService('ReplicatedStorage'):WaitForChild('RemoteEvents'):WaitForChild('UnequipItem'):FireServer(v.Name) end
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("W25 Moth Legwarmers")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("W25 Moth Legwarmers", "1", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("W25 Moth Legwarmers", "2", Color3.new(0.969, 0.839, 0.831))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("W25 Moth Legwarmers", "3", Color3.new(0.980, 0.906, 0.878))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("W25 Moth Legwarmers", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Ribbon Set - Corset Top")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "2", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "3", Color3.new(1.000, 0.922, 0.898))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "4", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "5", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Corset Top", "6", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Ribbon Set - Corset Top", 1, {["Bows"] = "On"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Bag With Fluff")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Bag With Fluff", "1", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Bag With Fluff", "2", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Bag With Fluff", "3", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Bag With Fluff", 3)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Fur Legs")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Fur Legs", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Fur Legs", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Winter: Fur Demonia Boots DIONCELLA")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Fur Demonia Boots DIONCELLA", "1", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Fur Demonia Boots DIONCELLA", "2", Color3.new(1.000, 1.000, 1.000))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Fur Demonia Boots DIONCELLA", "3", Color3.new(0.988, 0.914, 0.886))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Fur Demonia Boots DIONCELLA", "4", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Fur Demonia Boots DIONCELLA", "5", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Winter: Fur Demonia Boots DIONCELLA", 1, {["Flat"] = "Off"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Ribbon Set - Skirt ")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Skirt ", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Ribbon Set - Skirt ", "2", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Ribbon Set - Skirt ", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Crystal Choker")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Crystal Choker", "1", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Crystal Choker", "2", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Crystal Choker", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Everlasting Love Shoes")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Everlasting Love Shoes", "1", Color3.new(0.973, 0.973, 0.973))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Everlasting Love Shoes", "2", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Everlasting Love Shoes", "3", Color3.new(0.514, 0.314, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Everlasting Love Shoes", "4", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Everlasting Love Shoes", 2)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Kissy Lips Bodysuit")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Kissy Lips Bodysuit", "1", Color3.new(0.902, 0.929, 1.000))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Kissy Lips Bodysuit", "2", Color3.new(0.906, 0.835, 0.812))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Kissy Lips Bodysuit", "3", Color3.new(0.902, 0.831, 0.808))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Kissy Lips Bodysuit", "4", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Kissy Lips Bodysuit", "5", Color3.new(1.000, 1.000, 1.000))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Kissy Lips Bodysuit", 3, {["Kiss"] = "On"}, {["Thick"] = "Off"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("H25- Hair Heavenly Concept")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("H25- Hair Heavenly Concept", "1", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("H25- Hair Heavenly Concept", "2", Color3.new(0.416, 0.290, 0.227))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("H25- Hair Heavenly Concept", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Lashes")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Lashes", "1", Color3.new(0.000, 0.000, 0.000))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Lashes", 7)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("DTI x BRAT: Brat Staps")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("DTI x BRAT: Brat Staps", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("DTI x BRAT: Brat Staps", "2", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("DTI x BRAT: Brat Staps", "3", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("DTI x BRAT: Brat Staps", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("- Hair Huni Cute")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("- Hair Huni Cute", "1", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("- Hair Huni Cute", "2", Color3.new(0.588, 0.408, 0.322))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("- Hair Huni Cute", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Pearl Necklace")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Pearl Necklace", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Pearl Necklace", "2", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Pearl Necklace", "3", "rbxassetid://97110727711883")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Pearl Necklace", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Winter: Cute Beret")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Cute Beret", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Cute Beret", "2", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Winter: Cute Beret", "3", "rbxassetid://97110727711883")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Winter: Cute Beret", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("H25- Hair Braided Goddess")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("H25- Hair Braided Goddess", "1", Color3.new(0.369, 0.255, 0.200))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("H25- Hair Braided Goddess", "2", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("H25- Hair Braided Goddess", 3)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Butterfly Girl Sleeves")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Butterfly Girl Sleeves", "1", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Butterfly Girl Sleeves", "2", Color3.new(0.474, 0.288, 0.182))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Butterfly Girl Sleeves", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Heart Hoop Earings")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Heart Hoop Earings", "1", "rbxassetid://97110727711883")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Heart Hoop Earings", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("RoseSetCorset")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("RoseSetCorset", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("RoseSetCorset", "2", Color3.new(0.906, 0.835, 0.812))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("RoseSetCorset", "3", Color3.new(0.949, 0.878, 0.851))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("RoseSetCorset", 0)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("CagedHeartDress")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("CagedHeartDress", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("CagedHeartDress", "2", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("CagedHeartDress", "3", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("CagedHeartDress", "4", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("CagedHeartDress", 1, {["Strap"] = "On"}, {["Cage"] = "On"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("^^DiorBow")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("^^DiorBow", "1", "rbxassetid://90108289234845")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("^^DiorBow", "2", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("^^DiorBow", "3", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("^^DiorBow", "4", Color3.new(0.835, 0.702, 0.988))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("^^DiorBow", 5, {["Ribbon_1_Glitter"] = "Off"}, {["Ribbon_2_Glitter"] = "Off"}, {["Star_Glittery"] = "Off"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("Cupid Top")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Cupid Top", "1", Color3.new(1.000, 0.616, 0.659))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Cupid Top", "2", Color3.new(0.467, 0.859, 1.000))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Cupid Top", "3", Color3.new(1.000, 0.541, 0.612))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Cupid Top", "4", Color3.new(0.906, 0.835, 0.812))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("Cupid Top", "5", Color3.new(0.471, 0.325, 0.259))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("Cupid Top", 4, {["Jewels"] = "On"}, {["Layer"] = "On"}, {["Veil"] = "On"}, {["Rose"] = "On"})
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("African Arm Jewelry")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("African Arm Jewelry", "1", "rbxassetid://116702265463400")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("African Arm Jewelry", "2", Color3.new(0.973, 0.843, 0.835))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("African Arm Jewelry", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("EquipItem"):FireServer("NewYearHair")
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("NewYearHair", "1", Color3.new(0.369, 0.255, 0.200))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccessory"):FireServer("NewYearHair", "2", Color3.new(0.361, 0.251, 0.196))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("DressUpToggle"):FireServer("NewYearHair", 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ChangeSkintone"):FireServer(Color3.new(0.356863, 0.247059, 0.196078))
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Eyes", 51, 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Eyes", 51, 2)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Eyebrows", 77, 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Contour", 57, 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 386, 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 388, 2)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 377, 3)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 3, 4)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 286, 5)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Touches", 205, 6)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Lips", 186, 1)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Lips", 186, 2)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("CustomMakeup"):FireServer("Lips", 186, 3)
game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("ColorAccesso
